// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.AdobeMaterialsThinTransparency;

/// <summary>
/// glTF extension that defines properties to model physically plausible optical transparency.
/// </summary>
[Serializable]
public class GlTFADOBEMaterialsThinTransparency : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The base percentage of non-specularly reflected light that is transmitted through the surface. i.e. of the light that penetrates a surface (isn't specularly reflected), what percentage is transmitted and not diffusely re-emitted from the surface?
    /// </summary>
    public float? TransmissionFactor { get; set; }

    /// <inheritdoc cref="TransmissionFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float TransmissionFactorOrDefault => TransmissionFactor ?? 1F;

    /// <summary>
    /// The percentage of non-specularly reflected light that is transmitted through the surface. i.e. of the light that penetrates a surface (isn't specularly reflected), what percentage is transmitted and not diffusely re-emitted from the surface? This will be multiplied by the transmissionFactor.
    /// </summary>
    public glTFNet.Models.TextureInfo? TransmissionTexture { get; set; }

    /// <summary>
    /// The average index of refraction of the material, ignoring differences between frequencies of light. Default of 1.33 is for liquid water.
    /// </summary>
    public float? Ior { get; set; }

    /// <inheritdoc cref="Ior"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float IorOrDefault => Ior ?? 1.33F;
}