// <auto-generated/>
#nullable enable
namespace glTFNet.Models.Extensions.Khronos.KhrMaterialsClearcoat;

/// <summary>
/// glTF extension that defines the clearcoat material layer.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsClearcoat : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The clearcoat layer intensity (aka opacity) of the material. A value of 0.0 means the material has no clearcoat layer enabled.
    /// </summary>
    public float? ClearcoatFactor { get; set; }

    /// <inheritdoc cref="ClearcoatFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float ClearcoatFactorOrDefault => ClearcoatFactor ?? 0F;

    /// <summary>
    /// The clearcoat layer intensity texture. These values are sampled from the R channel.  The values are linear.  Use value 1.0 if no texture is supplied.
    /// </summary>
    public glTFNet.Models.TextureInfo? ClearcoatTexture { get; set; }

    /// <summary>
    /// The clearcoat layer roughness of the material.
    /// </summary>
    public float? ClearcoatRoughnessFactor { get; set; }

    /// <inheritdoc cref="ClearcoatRoughnessFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float ClearcoatRoughnessFactorOrDefault => ClearcoatRoughnessFactor ?? 0F;

    /// <summary>
    /// The clearcoat layer roughness texture. These values are sampled from the G channel.  The values are linear.  Use value 1.0 if no texture is supplied.
    /// </summary>
    public glTFNet.Models.TextureInfo? ClearcoatRoughnessTexture { get; set; }

    /// <summary>
    /// A tangent space normal map for the clearcoat layer.  If desired, this may be a reference to the same normal map used by the base material.  If not supplied, no normal mapping is applied to the clear coat layer.
    /// </summary>
    public glTFNet.Models.MaterialNormalTextureInfo? ClearcoatNormalTexture { get; set; }
}