// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl;

/// <summary>
/// Instances of shading techniques with external shader programs along with their parameterized values.  Shading techniques describe data types and semantics for GLSL vertex and fragment shader programs.
/// </summary>
[Serializable]
public class GlTFKHRTechniquesWebgl : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// An array of `Program` objects.
    /// </summary>
    public required List<Program> Programs { get; set; }

    /// <summary>
    /// An array of `Shader` objects.
    /// </summary>
    public required List<Shader> Shaders { get; set; }

    /// <summary>
    /// An array of `Technique` objects.  A technique is a template for a material appearance.
    /// </summary>
    public required List<Technique> Techniques { get; set; }
}