// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMeshoptCompression;

/// <summary>
/// Compressed data for bufferView.
/// </summary>
[Serializable]
public class BufferViewKHRMeshoptCompression : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The index of the buffer with compressed data.
    /// </summary>
    public required int Buffer { get; set; }

    /// <summary>
    /// The offset into the buffer in bytes.
    /// </summary>
    public int? ByteOffset { get; set; }

    /// <inheritdoc cref="ByteOffset"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public int ByteOffsetOrDefault => ByteOffset ?? 0;

    /// <summary>
    /// The length of the compressed data in bytes.
    /// </summary>
    public required int ByteLength { get; set; }

    /// <summary>
    /// The stride, in bytes.
    /// </summary>
    public required int ByteStride { get; set; }

    /// <summary>
    /// The number of elements.
    /// </summary>
    public required int Count { get; set; }

    /// <summary>
    /// The compression mode.
    /// </summary>
    public required string Mode { get; set; }

    /// <summary>
    /// The compression filter.
    /// </summary>
    public string? Filter { get; set; }

    /// <inheritdoc cref="Filter"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public string FilterOrDefault => Filter ?? "NONE";
}