// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.FbGeometryMetadata;

[Serializable]
public class SceneBounds : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The bounding box corner with the numerically lowest scene-space coordinates
    /// </summary>
    public required System.Numerics.Vector3 Min { get; set; }

    /// <summary>
    /// The bounding box corner with the numerically highest scene-space coordinates
    /// </summary>
    public required System.Numerics.Vector3 Max { get; set; }
}