// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtMeshPrimitiveRestart;

/// <summary>
/// A group of primitives that can be drawn together using a single index buffer containing restart values
/// </summary>
[Serializable]
public class PrimitiveGroup : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The indices of the primitives that will be combined and drawn using a single set of indices. All properties except for `indices` (e.g., `material`, `mode`, and `attributes`) will be obtained from the first primitive in the list, and all other primitives in the list **MUST** have identical values for those properties. The `mode` must be TRIANGLE_FAN, TRIANGLE_STRIP, LINE_LOOP, or LINE_STRIP.
    /// </summary>
    public required List<int> Primitives { get; set; }

    /// <summary>
    /// The index of the accessor that contains the vertex indices. The accessor **MUST** have `SCALAR` type and an unsigned integer component type. The indices are permitted to include the maximal index value for the component type, indicating the start of a new primitive.
    /// </summary>
    public required int Indices { get; set; }
}