// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models.Extensions.Khronos.KhrMaterialsUnlit;

/// <summary>
/// glTF extension that defines the unlit material model.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsUnlit : glTFNet.Models.GlTFProperty
{
}