// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrLightsPunctual;

[Serializable]
public class GltfKHRLightsPunctual : glTFNet.Specifications.Models.GltfProperty
{
    public required List<Light> Lights { get; set; }
}