// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrLightsPunctual;

/// <summary>
/// A directional, point, or spot light.
/// </summary>
[Serializable]
public class Light : glTFNet.Models.GlTFChildOfRootProperty
{
    /// <summary>
    /// Color of the light source.
    /// </summary>
    public System.Numerics.Vector3? Color { get; set; }

    /// <inheritdoc cref="Color"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 ColorOrDefault => Color ?? new(1F, 1F, 1F);

    /// <summary>
    /// Intensity of the light source. `point` and `spot` lights use luminous intensity in candela (lm/sr) while `directional` lights use illuminance in lux (lm/m^2)
    /// </summary>
    public float? Intensity { get; set; }

    /// <inheritdoc cref="Intensity"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float IntensityOrDefault => Intensity ?? 1F;

    public LightSpot? Spot { get; set; }

    /// <summary>
    /// Specifies the light type.
    /// </summary>
    public required string Type { get; set; }

    /// <summary>
    /// A distance cutoff at which the light's intensity may be considered to have reached zero.
    /// </summary>
    public float? Range { get; set; }
}