// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrLightsPunctual;

[Serializable]
public class NodeKHRLightsPunctual : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The id of the light referenced by this node.
    /// </summary>
    public required int Light { get; set; }
}