// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegSceneDynamic;

/// <summary>
/// glTF extension to expose dynamic scene updates using the JSON patch protocol with MPEG media
/// </summary>
[Serializable]
public class MPEGSceneDynamic : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// The index of the media in `MPEG_media` that provides dynamic scene update information.
    /// </summary>
    public required int Media { get; set; }

    /// <summary>
    /// The index of a track of media in `MPEG_media` that provides dynamic scene update information. The track samples as defined in ISO/IEC 23090-14 contain scene description updates and provide timing to perform these updates. If track is not provided, it shall be assumed that all tracks provided by the referenced media object are used to provide the update samples.
    /// </summary>
    public int? Track { get; set; }
}