// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrDracoMeshCompression;

[Serializable]
public class MeshPrimitiveKHRDracoMeshCompression : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The index of the bufferView.
    /// </summary>
    public required int BufferView { get; set; }

    /// <summary>
    /// A dictionary object, where each key corresponds to an attribute and its unique attribute id stored in the compressed geometry.
    /// </summary>
    public required Dictionary<string, int> Attributes { get; set; }
}