// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Archived.Models.KhrXmp;

/// <summary>
/// Metadata about the glTF asset.
/// </summary>
[Serializable]
public class GlTFKHRXmp : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// Dictionary mapping XMP namespace names to the URI where they are defined
    /// </summary>
    public required Dictionary<string, object> @context { get; set; }
    public required List<Dictionary<string, object>> Packets { get; set; }
}