// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Archived.Models.KhrXmp;

/// <summary>
/// References an XMP packet listed in `KHR_xmp glTF extension`
/// </summary>
[Serializable]
public class NodeKHRXmp : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The id of the XMP packet referenced by this node.
    /// </summary>
    public required int Packet { get; set; }
}