// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Archived.Models.KhrMaterialsPbrspecularglossiness;

/// <summary>
/// glTF extension that defines the specular-glossiness material model from Physically-Based Rendering (PBR) methodology.
/// </summary>
[Serializable]
public class GltfKHRMaterialsPbrSpecularGlossiness : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The RGBA components of the reflected diffuse color of the material. Metals have a diffuse value of `[0.0, 0.0, 0.0]`. The fourth component (A) is the alpha coverage of the material. The `alphaMode` property specifies how alpha is interpreted. The values are linear.
    /// </summary>
    public System.Numerics.Vector4? DiffuseFactor { get; set; }

    /// <inheritdoc cref="DiffuseFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector4 DiffuseFactorOrDefault => DiffuseFactor ?? new(1F, 1F, 1F, 1F);

    /// <summary>
    /// The diffuse texture. This texture contains RGB components of the reflected diffuse color of the material encoded with the sRGB transfer function. If the fourth component (A) is present, it represents the linear alpha coverage of the material. Otherwise, an alpha of 1.0 is assumed. The `alphaMode` property specifies how alpha is interpreted. The stored texels must not be premultiplied.
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? DiffuseTexture { get; set; }

    /// <summary>
    /// The specular RGB color of the material. This value is linear.
    /// </summary>
    public System.Numerics.Vector3? SpecularFactor { get; set; }

    /// <inheritdoc cref="SpecularFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 SpecularFactorOrDefault => SpecularFactor ?? new(1F, 1F, 1F);

    /// <summary>
    /// The glossiness or smoothness of the material. A value of 1.0 means the material has full glossiness or is perfectly smooth. A value of 0.0 means the material has no glossiness or is completely rough. This value is linear.
    /// </summary>
    public float? GlossinessFactor { get; set; }

    /// <inheritdoc cref="GlossinessFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float GlossinessFactorOrDefault => GlossinessFactor ?? 1F;

    /// <summary>
    /// The specular-glossiness texture is an RGBA texture, containing the specular color (RGB) encoded with the sRGB transfer function and the linear glossiness value (A).
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? SpecularGlossinessTexture { get; set; }
}