// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

/// <summary>
/// Sparse storage of accessor values that deviate from their initialization value.
/// </summary>
[Serializable]
public class AccessorSparse : GltfProperty
{
    /// <summary>
    /// Number of deviating accessor values stored in the sparse array.
    /// </summary>
    public required int Count { get; set; }

    /// <summary>
    /// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `count`. Indices **MUST** strictly increase.
    /// </summary>
    public required AccessorSparseIndices Indices { get; set; }

    /// <summary>
    /// An object pointing to a buffer view containing the deviating accessor values.
    /// </summary>
    public required AccessorSparseValues Values { get; set; }
}