// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

/// <summary>
/// A typed view into a buffer view that contains raw binary data.
/// </summary>
[Serializable]
public class Accessor : GlTFChildOfRootProperty
{
    /// <summary>
    /// The index of the buffer view. When undefined, the accessor **MUST** be initialized with zeros; `sparse` property or extensions **MAY** override zeros with actual values.
    /// </summary>
    public int? BufferView { get; set; }

    /// <summary>
    /// The offset relative to the start of the buffer view in bytes.  This **MUST** be a multiple of the size of the component datatype. This property **MUST NOT** be defined when `bufferView` is undefined.
    /// </summary>
    public int? ByteOffset { get; set; }

    /// <inheritdoc cref="ByteOffset"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public int ByteOffsetOrDefault => ByteOffset ?? 0;

    /// <summary>
    /// The datatype of the accessor's components.  UNSIGNED_INT type **MUST NOT** be used for any accessor that is not referenced by `mesh.primitive.indices`.
    /// </summary>
    public required AccessorComponentType ComponentType { get; set; }

    /// <summary>
    /// Specifies whether integer data values are normalized (`true`) to [0, 1] (for unsigned types) or to [-1, 1] (for signed types) when they are accessed. This property **MUST NOT** be set to `true` for accessors with `FLOAT` or `UNSIGNED_INT` component type.
    /// </summary>
    public bool? Normalized { get; set; }

    /// <inheritdoc cref="Normalized"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public bool NormalizedOrDefault => Normalized ?? false;

    /// <summary>
    /// The number of elements referenced by this accessor, not to be confused with the number of bytes or number of components.
    /// </summary>
    public required int Count { get; set; }

    /// <summary>
    /// Specifies if the accessor's elements are scalars, vectors, or matrices.
    /// </summary>
    public required AccessorType Type { get; set; }

    /// <summary>
    /// Maximum value of each component in this accessor.  Array elements **MUST** be treated as having the same data type as accessor's `componentType`. Both `min` and `max` arrays have the same length.  The length is determined by the value of the `type` property; it can be 1, 2, 3, 4, 9, or 16.
    /// `normalized` property has no effect on array values: they always correspond to the actual values stored in the buffer. When the accessor is sparse, this property **MUST** contain maximum values of accessor data with sparse substitution applied.
    /// </summary>
    public List<float>? Max { get; set; }

    /// <summary>
    /// Minimum value of each component in this accessor.  Array elements **MUST** be treated as having the same data type as accessor's `componentType`. Both `min` and `max` arrays have the same length.  The length is determined by the value of the `type` property; it can be 1, 2, 3, 4, 9, or 16.
    /// `normalized` property has no effect on array values: they always correspond to the actual values stored in the buffer. When the accessor is sparse, this property **MUST** contain minimum values of accessor data with sparse substitution applied.
    /// </summary>
    public List<float>? Min { get; set; }

    /// <summary>
    /// Sparse storage of elements that deviate from their initialization value.
    /// </summary>
    public AccessorSparse? Sparse { get; set; }
}