// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Specifications.Converters.JsonStringEnumMemberConverter<AnimationChannelTargetPath>))]
public enum AnimationChannelTargetPath
{
    [System.Runtime.Serialization.EnumMember(Value = "translation")]
    Translation,
    [System.Runtime.Serialization.EnumMember(Value = "rotation")]
    Rotation,
    [System.Runtime.Serialization.EnumMember(Value = "scale")]
    Scale,
    [System.Runtime.Serialization.EnumMember(Value = "weights")]
    Weights
}