// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

public enum BufferViewTarget
{
    /// <summary>
    /// ARRAY_BUFFER
    /// </summary>
    ArrayBuffer = 34962,
    /// <summary>
    /// ELEMENT_ARRAY_BUFFER
    /// </summary>
    ElementArrayBuffer = 34963
}