// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

/// <summary>
/// JSON object with extension-specific objects.
/// </summary>
[Serializable]
public class Extension : Dictionary<string, object>
{
}