// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

[Serializable]
public class GltfProperty
{
    public Extension? Extensions { get; set; }
    public object? Extras { get; set; }
}