// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

public enum SamplerMinFilter
{
    /// <summary>
    /// NEAREST
    /// </summary>
    Nearest = 9728,
    /// <summary>
    /// LINEAR
    /// </summary>
    Linear = 9729,
    /// <summary>
    /// NEAREST_MIPMAP_NEAREST
    /// </summary>
    NearestMipmapNearest = 9984,
    /// <summary>
    /// LINEAR_MIPMAP_NEAREST
    /// </summary>
    LinearMipmapNearest = 9985,
    /// <summary>
    /// NEAREST_MIPMAP_LINEAR
    /// </summary>
    NearestMipmapLinear = 9986,
    /// <summary>
    /// LINEAR_MIPMAP_LINEAR
    /// </summary>
    LinearMipmapLinear = 9987
}