// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Specifications.Models;

/// <summary>
/// The root nodes of a scene.
/// </summary>
[Serializable]
public class Scene : GltfChildOfRootProperty
{
    /// <summary>
    /// The indices of each root node.
    /// </summary>
    public List<int>? Nodes { get; set; }
}