// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtTextureWebp;

/// <summary>
/// glTF extension to specify textures using the WebP image format.
/// </summary>
[Serializable]
public class GltfEXTTextureWebp : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The index of the WebP image.
    /// </summary>
    public int? Source { get; set; }
}