// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsVariants;

/// <summary>
/// glTF extension that defines a material variations for mesh primitives
/// </summary>
[Serializable]
public class GltfKHRMaterialsVariants : glTFNet.Specifications.Models.GltfProperty
{
    public required List<glTFNet.Specifications.Models.GltfChildOfRootProperty> Variants { get; set; }
}