// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsVariants;

[Serializable]
public class MeshPrimitiveKHRMaterialsVariants : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// An array of object values that associate an indexed material to a set of variants.
    /// </summary>
    public required List<glTFNet.Specifications.Models.GlTFProperty> Mappings { get; set; }
}