// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtTextureAstc;

/// <summary>
/// glTF extension to specify textures using the KTX v2 images with ASTC compression.
/// </summary>
[Serializable]
public class TextureEXTTextureAstc : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The index of the image which points to a KTX v2 resource with ASTC compression.
    /// </summary>
    public int? Source { get; set; }
}