// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MsftPackingNormalroughnessmetallic;

/// <summary>
/// glTF extension the specifies a packing of normal, roughness and metallic in a single texture.
/// </summary>
[Serializable]
public class GlTFMSFTPackingNormalRoughnessMetallic : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// A texture with the packing Normal (RG), Roughness (B), Metallic (A).
    /// </summary>
    public object? NormalRoughnessMetallicTexture { get; set; }
}