// <auto-generated/>
#nullable enable
namespace glTFNet.Models.Extensions.Khronos.KhrDracoMeshCompression;

[Serializable]
public class MeshPrimitiveKHRDracoMeshCompression : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The index of the bufferView.
    /// </summary>
    public required int BufferView { get; set; }

    /// <summary>
    /// A dictionary object, where each key corresponds to an attribute and its unique attribute id stored in the compressed geometry.
    /// </summary>
    public required Dictionary<string, int> Attributes { get; set; }
}