namespace glTFNet.Generator.Types;

/// <summary>
/// Defines a type that is generated by the schema.
/// </summary>
public interface ISchemaGeneratedType : ISchemaType
{
    /// <summary>
    /// Gets the name of the generated type.
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Gets the namespace.
    /// </summary>
    string Namespace { get; }
}