// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

public enum AccessorSparseIndicesComponentType
{
    /// <summary>
    /// UNSIGNED_BYTE
    /// </summary>
    UnsignedByte = 5121,
    /// <summary>
    /// UNSIGNED_SHORT
    /// </summary>
    UnsignedShort = 5123,
    /// <summary>
    /// UNSIGNED_INT
    /// </summary>
    UnsignedInt = 5125
}