// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

/// <summary>
/// An object pointing to a buffer view containing the indices of deviating accessor values. The number of indices is equal to `accessor.sparse.count`. Indices **MUST** strictly increase.
/// </summary>
[Serializable]
public class AccessorSparseIndices : GlTFProperty
{
    /// <summary>
    /// The index of the buffer view with sparse indices. The referenced buffer view **MUST NOT** have its `target` or `byteStride` properties defined. The buffer view and the optional `byteOffset` **MUST** be aligned to the `componentType` byte length.
    /// </summary>
    public required int BufferView { get; set; }

    /// <summary>
    /// The offset relative to the start of the buffer view in bytes.
    /// </summary>
    public int? ByteOffset { get; set; }

    /// <inheritdoc cref="ByteOffset"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public int ByteOffsetOrDefault => ByteOffset ?? 0;

    /// <summary>
    /// The indices data type.
    /// </summary>
    public required AccessorSparseIndicesComponentType ComponentType { get; set; }
}