// <auto-generated/>
#nullable enable
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<AccessorType>))]
public enum AccessorType
{
    [System.Runtime.Serialization.EnumMember(Value = "SCALAR")]
    Scalar,
    [System.Runtime.Serialization.EnumMember(Value = "VEC2")]
    Vec2,
    [System.Runtime.Serialization.EnumMember(Value = "VEC3")]
    Vec3,
    [System.Runtime.Serialization.EnumMember(Value = "VEC4")]
    Vec4,
    [System.Runtime.Serialization.EnumMember(Value = "MAT2")]
    Mat2,
    [System.Runtime.Serialization.EnumMember(Value = "MAT3")]
    Mat3,
    [System.Runtime.Serialization.EnumMember(Value = "MAT4")]
    Mat4
}