// <auto-generated/>
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<AnimationSamplerInterpolation>))]
public enum AnimationSamplerInterpolation
{
    /// <summary>
    /// The animated values are linearly interpolated between keyframes. When targeting a rotation, spherical linear interpolation (slerp) **SHOULD** be used to interpolate quaternions. The number of output elements **MUST** equal the number of input elements.
    /// </summary>
    [System.Text.Json.Serialization.JsonStringEnumMemberName("LINEAR")]
    Linear,
    /// <summary>
    /// The animated values remain constant to the output of the first keyframe, until the next keyframe. The number of output elements **MUST** equal the number of input elements.
    /// </summary>
    [System.Text.Json.Serialization.JsonStringEnumMemberName("STEP")]
    Step,
    /// <summary>
    /// The animation's interpolation is computed using a cubic spline with specified tangents. The number of output elements **MUST** equal three times the number of input elements. For each input element, the output stores three elements, an in-tangent, a spline vertex, and an out-tangent. There **MUST** be at least two keyframes when using this interpolation.
    /// </summary>
    [System.Text.Json.Serialization.JsonStringEnumMemberName("CUBICSPLINE")]
    Cubicspline
}