// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

/// <summary>
/// A buffer points to binary geometry, animation, or skins.
/// </summary>
[Serializable]
public class Buffer : GlTFChildOfRootProperty
{
    /// <summary>
    /// The URI (or IRI) of the buffer.  Relative paths are relative to the current glTF asset.  Instead of referencing an external file, this field **MAY** contain a `data:`-URI.
    /// </summary>
    public string? Uri { get; set; }

    /// <summary>
    /// The length of the buffer in bytes.
    /// </summary>
    public required int ByteLength { get; set; }
}