// <auto-generated/>
namespace glTFNet.Models;

/// <summary>
/// An orthographic camera containing properties to create an orthographic projection matrix.
/// </summary>
[Serializable]
public class CameraOrthographic : GlTFProperty
{
    /// <summary>
    /// The floating-point horizontal magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    /// </summary>
    public required float Xmag { get; set; }

    /// <summary>
    /// The floating-point vertical magnification of the view. This value **MUST NOT** be equal to zero. This value **SHOULD NOT** be negative.
    /// </summary>
    public required float Ymag { get; set; }

    /// <summary>
    /// The floating-point distance to the far clipping plane. This value **MUST NOT** be equal to zero. `zfar` **MUST** be greater than `znear`.
    /// </summary>
    public required float Zfar { get; set; }

    /// <summary>
    /// The floating-point distance to the near clipping plane.
    /// </summary>
    public required float Znear { get; set; }
}