// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<CameraType>))]
public enum CameraType
{
    [System.Runtime.Serialization.EnumMember(Value = "perspective")]
    Perspective,
    [System.Runtime.Serialization.EnumMember(Value = "orthographic")]
    Orthographic
}