// <auto-generated/>
#nullable enable
namespace glTFNet.Models;

/// <summary>
/// JSON object with extension-specific objects.
/// </summary>
[Serializable]
public class Extension : Dictionary<string, object>
{
}