// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

/// <summary>
/// The root object for a glTF asset.
/// </summary>
[Serializable]
public class GlTF : GlTFProperty
{
    /// <summary>
    /// Names of glTF extensions used in this asset.
    /// </summary>
    public List<string>? ExtensionsUsed { get; set; }

    /// <summary>
    /// Names of glTF extensions required to properly load this asset.
    /// </summary>
    public List<string>? ExtensionsRequired { get; set; }

    /// <summary>
    /// An array of accessors.  An accessor is a typed view into a bufferView.
    /// </summary>
    public List<Accessor>? Accessors { get; set; }

    /// <summary>
    /// An array of keyframe animations.
    /// </summary>
    public List<Animation>? Animations { get; set; }

    /// <summary>
    /// Metadata about the glTF asset.
    /// </summary>
    public required Asset Asset { get; set; }

    /// <summary>
    /// An array of buffers.  A buffer points to binary geometry, animation, or skins.
    /// </summary>
    public List<Buffer>? Buffers { get; set; }

    /// <summary>
    /// An array of bufferViews.  A bufferView is a view into a buffer generally representing a subset of the buffer.
    /// </summary>
    public List<BufferView>? BufferViews { get; set; }

    /// <summary>
    /// An array of cameras.  A camera defines a projection matrix.
    /// </summary>
    public List<Camera>? Cameras { get; set; }

    /// <summary>
    /// An array of images.  An image defines data used to create a texture.
    /// </summary>
    public List<Image>? Images { get; set; }

    /// <summary>
    /// An array of materials.  A material defines the appearance of a primitive.
    /// </summary>
    public List<Material>? Materials { get; set; }

    /// <summary>
    /// An array of meshes.  A mesh is a set of primitives to be rendered.
    /// </summary>
    public List<Mesh>? Meshes { get; set; }

    /// <summary>
    /// An array of nodes.
    /// </summary>
    public List<Node>? Nodes { get; set; }

    /// <summary>
    /// An array of samplers.  A sampler contains properties for texture filtering and wrapping modes.
    /// </summary>
    public List<Sampler>? Samplers { get; set; }

    /// <summary>
    /// The index of the default scene.  This property **MUST NOT** be defined, when `scenes` is undefined.
    /// </summary>
    public int? Scene { get; set; }

    /// <summary>
    /// An array of scenes.
    /// </summary>
    public List<Scene>? Scenes { get; set; }

    /// <summary>
    /// An array of skins.  A skin is defined by joints and matrices.
    /// </summary>
    public List<Skin>? Skins { get; set; }

    /// <summary>
    /// An array of textures.
    /// </summary>
    public List<Texture>? Textures { get; set; }
}