// <auto-generated/>
#nullable enable
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<ImageMimeType>))]
public enum ImageMimeType
{
    [System.Runtime.Serialization.EnumMember(Value = "image/jpeg")]
    ImageJpeg,
    [System.Runtime.Serialization.EnumMember(Value = "image/png")]
    ImagePng
}