// <auto-generated/>
#nullable enable
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ImageMimeType>))]
public enum ImageMimeType
{
    [System.Text.Json.Serialization.JsonStringEnumMemberName("image/jpeg")]
    ImageJpeg,
    [System.Text.Json.Serialization.JsonStringEnumMemberName("image/png")]
    ImagePng
}