// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<MaterialAlphaMode>))]
public enum MaterialAlphaMode
{
    /// <summary>
    /// The alpha value is ignored, and the rendered output is fully opaque.
    /// </summary>
    [System.Runtime.Serialization.EnumMember(Value = "OPAQUE")]
    Opaque,
    /// <summary>
    /// The rendered output is either fully opaque or fully transparent depending on the alpha value and the specified `alphaCutoff` value; the exact appearance of the edges **MAY** be subject to implementation-specific techniques such as "`Alpha-to-Coverage`".
    /// </summary>
    [System.Runtime.Serialization.EnumMember(Value = "MASK")]
    Mask,
    /// <summary>
    /// The alpha value is used to composite the source and destination areas. The rendered output is combined with the background using the normal painting operation (i.e. the Porter and Duff over operator).
    /// </summary>
    [System.Runtime.Serialization.EnumMember(Value = "BLEND")]
    Blend
}