// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsSpecular;

/// <summary>
/// glTF extension that defines the strength of the specular reflection.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsSpecular : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// This parameter scales the amount of specular reflection on non-metallic surfaces. It has no effect on metals.
    /// </summary>
    public float? SpecularFactor { get; set; }

    /// <inheritdoc cref="SpecularFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float SpecularFactorOrDefault => SpecularFactor ?? 1F;

    /// <summary>
    /// A texture that defines the specular factor in the alpha channel. This will be multiplied by specularFactor.
    /// </summary>
    public glTFNet.Models.TextureInfo? SpecularTexture { get; set; }

    /// <summary>
    /// This is an additional RGB color parameter that tints the specular reflection of non-metallic surfaces. At grazing angles, the reflection still blends to white, and the parameter has not effect on metals. The value is linear.
    /// </summary>
    public System.Numerics.Vector3? SpecularColorFactor { get; set; }

    /// <inheritdoc cref="SpecularColorFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 SpecularColorFactorOrDefault => SpecularColorFactor ?? new(1F, 1F, 1F);

    /// <summary>
    /// A texture that defines the specular color in the RGB channels (encoded in sRGB). This will be multiplied by specularColorFactor.
    /// </summary>
    public glTFNet.Models.TextureInfo? SpecularColorTexture { get; set; }
}