// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.AgiStkMetadata;

/// <summary>
/// glTF Extension that defines metadata for use with STK (Systems Tool Kit).
/// </summary>
[Serializable]
public class GltfAGIStkMetadata : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// An array of solar panel groups.
    /// </summary>
    public List<SolarPanelGroup>? SolarPanelGroups { get; set; }
}