// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Archived;

[System.Text.Json.Serialization.JsonSourceGenerationOptions(
PropertyNamingPolicy = System.Text.Json.Serialization.JsonKnownNamingPolicy.CamelCase,
Converters = [typeof(glTFNet.Specifications.Converters.Vector2Converter), typeof(glTFNet.Specifications.Converters.Vector3Converter), typeof(glTFNet.Specifications.Converters.Vector4Converter), typeof(glTFNet.Specifications.Converters.QuaternionConverter), typeof(glTFNet.Specifications.Converters.Matrix4x4Converter)])]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrMaterialsPbrspecularglossiness.GltfKHRMaterialsPbrSpecularGlossiness))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.GltfKHRTechniquesWebgl))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.MaterialKHRTechniquesWebgl))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.Program))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.Shader))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.TechniqueAttribute))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.Technique))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrTechniquesWebgl.TechniqueUniform))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrXmp.GltfKHRXmp))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Archived.Models.KhrXmp.NodeKHRXmp))]
public partial class GltfSerializerContext : System.Text.Json.Serialization.JsonSerializerContext
{
}