// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegViewportRecommended;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<MPEGViewportRecommendedViewportType>))]
public enum MPEGViewportRecommendedViewportType
{
    [System.Runtime.Serialization.EnumMember(Value = "perspective")]
    Perspective,
    [System.Runtime.Serialization.EnumMember(Value = "orthographic")]
    Orthographic
}