// <auto-generated/>
#nullable enable
namespace glTFNet.Models.Extensions.Archived.KhrTechniquesWebgl;

/// <summary>
/// The technique to use for a material and any additional uniform values.
/// </summary>
[Serializable]
public class MaterialKHRTechniquesWebgl : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The index of the technique.
    /// </summary>
    public required int Technique { get; set; }

    /// <summary>
    /// Dictionary object of uniform values. Uniforms with the same name as the technique's uniform must conform to the referenced `type` and `count` (if present) properties, and override the technique's uniform value.  A uniform value must be supplied here if not present in the technique uniforms.
    /// </summary>
    public Dictionary<string, object>? Values { get; set; }
}