// <auto-generated/>
#nullable enable
namespace glTFNet.Models.Extensions.Archived.KhrTechniquesWebgl;

/// <summary>
/// A template for material appearances.
/// </summary>
[Serializable]
public class Technique : glTFNet.Models.GlTFChildOfRootProperty
{
    /// <summary>
    /// The index of the program.
    /// </summary>
    public required int Program { get; set; }

    /// <summary>
    /// A dictionary object of `Attribute` objects.  Each object defines an attribute input with a type and a semantic.
    /// </summary>
    public Dictionary<string, TechniqueAttribute>? Attributes { get; set; }

    /// <summary>
    /// A dictionary object of `Uniform` objects.  Each object defines a uniform input with a type and an optional semantic and value.
    /// </summary>
    public Dictionary<string, TechniqueUniform>? Uniforms { get; set; }
}