// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos;

[System.Text.Json.Serialization.JsonSourceGenerationOptions(
PropertyNamingPolicy = System.Text.Json.Serialization.JsonKnownNamingPolicy.CamelCase,
Converters = [typeof(glTFNet.Specifications.Converters.Vector2Converter), typeof(glTFNet.Specifications.Converters.Vector3Converter), typeof(glTFNet.Specifications.Converters.Vector4Converter), typeof(glTFNet.Specifications.Converters.QuaternionConverter), typeof(glTFNet.Specifications.Converters.Matrix4x4Converter)])]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrAnimationPointer.AnimationChannelTargetKHRAnimationPointer))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrDracoMeshCompression.MeshPrimitiveKHRDracoMeshCompression))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrGaussianSplatting.MeshPrimitiveKHRGaussianSplatting))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrLightsPunctual.GlTFKHRLightsPunctual))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrLightsPunctual.Light))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrLightsPunctual.LightSpot))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrLightsPunctual.NodeKHRLightsPunctual))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsAnisotropy.MaterialKHRMaterialsAnisotropy))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsClearcoat.MaterialKHRMaterialsClearcoat))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsDiffuseTransmission.MaterialKHRMaterialsDiffuseTransmission))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsDispersion.MaterialKHRMaterialsDispersion))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsEmissiveStrength.MaterialKHRMaterialsEmissiveStrength))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsIor.MaterialKHRMaterialsIor))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsIridescence.MaterialKHRMaterialsIridescence))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsSheen.MaterialKHRMaterialsSheen))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsSpecular.MaterialKHRMaterialsSpecular))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsTransmission.MaterialKHRMaterialsTransmission))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsUnlit.MaterialKHRMaterialsUnlit))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsVariants.GlTFKHRMaterialsVariants))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsVariants.MeshPrimitiveKHRMaterialsVariants))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMaterialsVolume.MaterialKHRMaterialsVolume))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMeshoptCompression.BufferKHRMeshoptCompression))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrMeshoptCompression.BufferViewKHRMeshoptCompression))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrNodeVisibility.NodeKHRNodeVisibility))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrTextureBasisu.TextureKHRTextureBasisu))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrTextureTransform.TextureInfoKHRTextureTransform))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrXmpJsonLd.KHRXmpJsonLd))]
[System.Text.Json.Serialization.JsonSerializable(typeof(glTFNet.Extensions.Khronos.Models.KhrXmpJsonLd.GlTFKHRXmpJsonLd))]
public partial class GlTFSerializerContext : System.Text.Json.Serialization.JsonSerializerContext
{
}