// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsUnlit;

/// <summary>
/// glTF extension that defines the unlit material model.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsUnlit : glTFNet.Specifications.Models.GltfProperty
{
}