// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrAnimationPointer;

/// <summary>
/// Extension object providing the JSON Pointer to the animated property.
/// </summary>
[Serializable]
public class AnimationChannelTargetKHRAnimationPointer : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// JSON pointer to the animated property. The animation channel path value **MUST** be `pointer`.
    /// </summary>
    public required string Pointer { get; set; }
}