// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MsftLod;

/// <summary>
/// glTF extension for specifying levels of detail (LOD).
/// </summary>
[Serializable]
public class GltfMSFTLod : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// Array containing the indices of progressively lower LOD nodes.
    /// </summary>
    public List<int>? Ids { get; set; }
}