// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegTextureVideo;

/// <summary>
/// glTF extension to specify textures using MPEG defined formats
/// </summary>
[Serializable]
public class MPEGTextureVideo : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// Provides a reference to the `accessor`, by specifying the accessor's index in accessors array, that describes the buffer where the decoded timed texture will be made available. The `accessor` shall have the `MPEG_accessor_timed` extension. The type, componentType, and count of the accessor depend on the width, height, and format.
    /// </summary>
    public required int Accessor { get; set; }

    /// <summary>
    /// Provides the maximum width of the texture.
    /// </summary>
    public required float Width { get; set; }

    /// <summary>
    /// Provides the maximum height of the texture.
    /// </summary>
    public required float Height { get; set; }

    /// <summary>
    /// Indicates the format of the pixel data for this video texture. The semantics of these values are defined in Table 8.3 of OpenGL 4.6 specification. The number of components shall match the type indicated by the referenced `accessor`. Normalization of the pixel data shall be indicated by the normalized attribute of the accessor.
    /// </summary>
    public MPEGTextureVideoFormat? Format { get; set; }

    /// <inheritdoc cref="Format"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public MPEGTextureVideoFormat FormatOrDefault => Format ?? MPEGTextureVideoFormat.Rgb;
}