// <auto-generated/>
#nullable enable
namespace glTFNet.Models.Extensions.Khronos.KhrMaterialsDispersion;

/// <summary>
/// glTF extension that defines the strength of dispersion.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsDispersion : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// This parameter defines dispersion in terms of the 20/Abbe number formulation.
    /// </summary>
    public float? Dispersion { get; set; }

    /// <inheritdoc cref="Dispersion"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float DispersionOrDefault => Dispersion ?? 0F;
}