// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtLightsIes;

/// <summary>
/// glTF extension that enables the use of IES light profiles.
/// </summary>
[Serializable]
public class GltfEXTLightsIes : glTFNet.Specifications.Models.GltfProperty
{
    public required List<LightProfile> Lights { get; set; }
}