// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtLightsIes;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Specifications.Converters.JsonStringEnumMemberConverter<LightProfileMimeType>))]
public enum LightProfileMimeType
{
    [System.Runtime.Serialization.EnumMember(Value = "application/x-ies-lm-63")]
    ApplicationXIesLm63
}