// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtLightsIes;

[Serializable]
public class NodeEXTLightsIes : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// The id of the light profile referenced by this node.
    /// </summary>
    public required int Light { get; set; }

    /// <summary>
    /// Non-negative factor to scale the light's intensity.
    /// </summary>
    public float? Multiplier { get; set; }

    /// <inheritdoc cref="Multiplier"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float MultiplierOrDefault => Multiplier ?? 1F;

    /// <summary>
    /// RGB value for the light's color in linear space.
    /// </summary>
    public System.Numerics.Vector3? Color { get; set; }

    /// <inheritdoc cref="Color"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 ColorOrDefault => Color ?? new(1F, 1F, 1F);
}