// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.AgiArticulations;

/// <summary>
/// glTF Extension that defines metadata for applying external analysis or effects to a model.
/// </summary>
[Serializable]
public class GltfAGIArticulations : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// An array of articulations.  An articulation indicates a named range of motion available to one or more nodes within the model.
    /// </summary>
    public List<Articulation>? Articulations { get; set; }
}