// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrXmpJsonLd;

/// <summary>
/// Metadata about the glTF asset.
/// </summary>
[Serializable]
public class GlTFKHRXmpJsonLd : glTFNet.Models.GlTFProperty
{
    public required List<Dictionary<string, object>> Packets { get; set; }
}