// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegAudioSpatial;

[Serializable]
public class MPEGAudioSpatialReverb : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// Indicates if the reverb unit can be bypassed if the audio renderer does not support it.
    /// </summary>
    public bool? Bypass { get; set; }

    /// <inheritdoc cref="Bypass"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public bool BypassOrDefault => Bypass ?? true;

    /// <summary>
    /// Array of items that contains reverb property objects describing reverb unit specific parameters
    /// </summary>
    public required List<MPEGAudioSpatialReverbProperty> Properties { get; set; }

    /// <summary>
    /// Delay in seconds from onset of source to onset of late reverberation for which DSR is provided.
    /// </summary>
    public float? Predelay { get; set; }

    /// <inheritdoc cref="Predelay"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float PredelayOrDefault => Predelay ?? 0F;
}