// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegAudioSpatial;

[Serializable]
public class MPEGAudioSpatialListener : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// A unique identifier of the audio listener in the scene.
    /// </summary>
    public required int Id { get; set; }
}