// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsSheen;

/// <summary>
/// glTF extension that defines the sheen material model.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsSheen : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// Color of the sheen layer (in linear space).
    /// </summary>
    public System.Numerics.Vector3? SheenColorFactor { get; set; }

    /// <inheritdoc cref="SheenColorFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 SheenColorFactorOrDefault => SheenColorFactor ?? new(0F, 0F, 0F);

    /// <summary>
    /// The sheen color (RGB) texture. Stored in channel RGB, the sheen color is in sRGB transfer function.
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? SheenColorTexture { get; set; }

    /// <summary>
    /// The sheen layer roughness of the material.
    /// </summary>
    public float? SheenRoughnessFactor { get; set; }

    /// <inheritdoc cref="SheenRoughnessFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float SheenRoughnessFactorOrDefault => SheenRoughnessFactor ?? 0F;

    /// <summary>
    /// The sheen roughness (Alpha) texture. Stored in alpha channel, the roughness value is in linear space.
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? SheenRoughnessTexture { get; set; }
}