// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtMeshManifold;

/// <summary>
/// glTF extension defines manifoldness for a mesh.
/// </summary>
[Serializable]
public class MeshEXTMeshManifold : glTFNet.Specifications.Models.GlTFProperty
{
    public required glTFNet.Specifications.Models.MeshPrimitive ManifoldPrimitive { get; set; }

    /// <summary>
    /// The index of the accessor that contains the vertex sparse indices for merging into a manifold.
    /// </summary>
    public int? MergeIndices { get; set; }

    /// <summary>
    /// The index of the accessor that contains the vertex sparse values for merging into a manifold.
    /// </summary>
    public int? MergeValues { get; set; }
}