// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsEmissiveStrength;

/// <summary>
/// glTF extension that adjusts the strength of emissive material properties.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsEmissiveStrength : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The strength adjustment to be multiplied with the material's emissive value.
    /// </summary>
    public float? EmissiveStrength { get; set; }

    /// <inheritdoc cref="EmissiveStrength"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float EmissiveStrengthOrDefault => EmissiveStrength ?? 1F;
}