// <auto-generated/>
namespace glTFNet.Models.Extensions.Khronos.KhrMaterialsTransmission;

/// <summary>
/// glTF extension that defines the optical transmission of a material.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsTransmission : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The base percentage of non-specularly reflected light that is transmitted through the surface. i.e. of the light that penetrates a surface (isn't specularly reflected), this is the percentage that is transmitted and not diffusely re-emitted.
    /// </summary>
    public float? TransmissionFactor { get; set; }

    /// <inheritdoc cref="TransmissionFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float TransmissionFactorOrDefault => TransmissionFactor ?? 0F;

    /// <summary>
    /// A texture that defines the transmission percentage of the surface, sampled from the R channel. These values are linear, and will be multiplied by transmissionFactor. This indicates the percentage of non-specularly reflected light that is transmitted through the surface. i.e. of the light that penetrates a surface (isn't specularly reflected), this is the percentage is transmitted and not diffusely re-emitted.
    /// </summary>
    public glTFNet.Models.TextureInfo? TransmissionTexture { get; set; }
}