// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Models.Extensions.Khronos.KhrLightsPunctual;

[Serializable]
public class GlTFKHRLightsPunctual : glTFNet.Models.GlTFProperty
{
    public required List<Light> Lights { get; set; }
}