// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.NvMaterialsMdl;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Specifications.Converters.JsonStringEnumMemberConverter<FunctionCallTypeModifier>))]
public enum FunctionCallTypeModifier
{
    [System.Runtime.Serialization.EnumMember(Value = "varying")]
    Varying,
    [System.Runtime.Serialization.EnumMember(Value = "uniform")]
    Uniform
}