// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.NvMaterialsMdl;

/// <summary>
/// glTF extension that enables using MDL materials.
/// </summary>
[Serializable]
public class GltfNVMaterialsMdl : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The list of all MDL modules.
    /// </summary>
    public List<Module>? Modules { get; set; }

    /// <summary>
    /// The list of all function calls.
    /// </summary>
    public List<FunctionCall>? FunctionCalls { get; set; }

    /// <summary>
    /// The list of all BSDF measurements.
    /// </summary>
    public List<BsdfMeasurement>? BsdfMeasurements { get; set; }
}