// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtLightsImageBased;

[Serializable]
public class GltfEXTLightsImageBased : glTFNet.Specifications.Models.GltfProperty
{
    public required List<ExtLightsImageBasedLight> Lights { get; set; }
}