// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.ExtLightsImageBased;

[Serializable]
public class SceneEXTLightsImageBased : glTFNet.Specifications.Models.GltfProperty
{
    /// <summary>
    /// The id of the light referenced by this scene.
    /// </summary>
    public required int Light { get; set; }
}