// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegMedia;

/// <summary>
/// Media used to create a texture, audio source or other objects in the scene.
/// </summary>
[Serializable]
public class MPEGMedia : glTFNet.Specifications.Models.GltfChildOfRootProperty
{
    /// <summary>
    /// An array of media. A media contains data referred by other object in a scene
    /// </summary>
    public required List<MPEGMediaMedia> Media { get; set; }
}