// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegMedia;

[System.Text.Json.Serialization.JsonConverter(typeof(glTFNet.Converters.JsonStringEnumMemberConverter<MPEGMediaMediaAlternativeMimeType>))]
public enum MPEGMediaMediaAlternativeMimeType
{
}