// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Vendor.Models.MpegMedia;

[Serializable]
public class MPEGMediaMediaAlternative : glTFNet.Models.GlTFProperty
{
    /// <summary>
    /// The uri of the media. Relative paths are relative to the .gltf file. If the reference media is a real-time media stream, then the uri may follow the referencing scheme defined in ISO/IEC 23090-14:Annex C. If the tracks element is present, the last part of the URI (i.e. the stream identifier such as the mid) is provided by the tracks information.
    /// </summary>
    public required string Uri { get; set; }

    /// <summary>
    /// The media's MIME type. The profiles parameter, as defined in IETF RFC6381, may be included as a part of the mimeType to specify the profile of the media container. (e.g. the profiles parameter indicates the DASH profile when the uri specifies a DASH manifest)
    /// </summary>
    public required MPEGMediaMediaAlternativeMimeType MimeType { get; set; }

    /// <summary>
    /// An array of items that lists the components of the referenced media source that are to be used. These can e.g. be a track number of an ISOBMFF, a DASH/CMAF SwitchingSet identifier, or a media id of an RTP stream.
    /// </summary>
    public List<MPEGMediaMediaAlternativeTrack>? Tracks { get; set; }

    /// <summary>
    /// An object that may contain any additional media-specific parameters.
    /// </summary>
    public object? ExtraParams { get; set; }
}