// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
namespace glTFNet.Extensions.Khronos.Models.KhrMaterialsDiffuseTransmission;

/// <summary>
/// glTF extension that defines the diffuse transmission of the material.
/// </summary>
[Serializable]
public class MaterialKHRMaterialsDiffuseTransmission : glTFNet.Specifications.Models.GlTFProperty
{
    /// <summary>
    /// The percentage of non-specularly reflected light that is transmitted through the surface via a Lambertian diffuse transmission.
    /// </summary>
    public float? DiffuseTransmissionFactor { get; set; }

    /// <inheritdoc cref="DiffuseTransmissionFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public float DiffuseTransmissionFactorOrDefault => DiffuseTransmissionFactor ?? 0F;

    /// <summary>
    /// A texture that defines the strength of the diffuse transmission effect, stored in the alpha (A) channel. Will be multiplied by the `diffuseTransmissionFactor` value.
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? DiffuseTransmissionTexture { get; set; }

    /// <summary>
    /// The color of the transmitted light.
    /// </summary>
    public System.Numerics.Vector3? DiffuseTransmissionColorFactor { get; set; }

    /// <inheritdoc cref="DiffuseTransmissionColorFactor"/>
    [System.Text.Json.Serialization.JsonIgnore]
    public System.Numerics.Vector3 DiffuseTransmissionColorFactorOrDefault => DiffuseTransmissionColorFactor ?? new(1F, 1F, 1F);

    /// <summary>
    /// A texture that defines the color of the transmitted light, stored in the RGB channels and encoded in sRGB. This texture will be multiplied by the `diffuseTransmissionColorFactor` value.
    /// </summary>
    public glTFNet.Specifications.Models.TextureInfo? DiffuseTransmissionColorTexture { get; set; }
}